//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Book_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string book_name { get; set; }
        public int author_id { get; set; }
        public double book_price { get; set; }
        public int category_id { get; set; }
        public int lang_id { get; set; }
        public int book_amount { get; set; }
        public string book_info { get; set; }
        public string book_photo { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual Language Language { get; set; }
    }
}
