//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Book_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string user_nick_name { get; set; }
        public string user_name { get; set; }
        public string user_surname { get; set; }
        public string user_password { get; set; }
        public string user_photo { get; set; }
        public string user_email { get; set; }
        public string user_tel { get; set; }
        public int user_status { get; set; }
    }
}
